# ________          __         .____                       .___
# \______ \   _____/  |_  _____|    |   _____    ____    __| _/
#  |    |  \ /  _ \   __\/  ___/    |   \__  \  /    \  / __ | 
#  |    `   (  <_> )  |  \___ \|    |___ / __ \|   |  \/ /_/ | 
# /_______  /\____/|__| /____  >_______ (____  /___|  /\____ | 
#         \/                 \/        \/    \/     \/      \/ 
# Welcome to DotsLand hyprland configuration!
# Everything about hyprland configuration can be found in configuration/ directory
# If you enjoy DotsLand please leave a star on my github repository! :3
# https://github.com/JustLivvu/DotsLand-hyprland

$config = $HOME/.config/hypr/configuration

source = $config/keybinds.conf
source = $config/windowrules.conf
source = $config/monitors.conf
source = $config/autostart.conf
source = $config/animations.conf
source = $config/settings.conf
source = $config/env.conf